name: "Test zig"
on:
    push:
        paths:
        - "**/*.zig"
jobs:
    test-zig:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Set up Zig
          with:
            version: 0.13.0
          uses: goto-bus-stop/setup-zig@v2
        - name: Lint zig
          run: zig fmt --check --color on .
        - name: Test zig
          run: zig build test --summary all
